theme: jekyll-theme-slate
title: João Wendling - Analista de Dados
description: Trabalhos realizados para diferentes clientes, usando Power BI, SQL, Looker Studio, Excel e Python
github:
  is_project_page: false
