theme: jekyll-theme-slate
title: João Wendling - Analista de Dados
description: Um pouco dos trabalhos que realizei e também arquivos de estudo. Power BI | Google Data Studio | Python
github:
  is_project_page: false
